### ISSUE TITLE
Feature: create endpoints to query sounds

### ISSUE THREAD

**Issue by takanome-dev** [Ruzie/soundcloud-info#23]
After a scan to the codebase, the only way to get info is to manually call a method in a class.
In my opinion, it will be great if we can create endpoints for each class to make it really simple for use.

Can you please tell me why you export everything in the index file??
Is this an api or a package (I'm a little bit confuse :sweat_smile: )??

**Comment by rilysh** [comment]
Do you mean `track`, `playlist`, `album` and `artist` endpoints or instead creating a new class directly calling methods for ex. `search(...)`? Any of them from here would be nice, though current code isn't anything harder in particular. Basically all these classes has a `get`, (except version info which is a function) so you need to initalize a new class and can use get. Parameters depends on what class you've initalized.

And I did export all these to an index file to make it more clean, I had separated all methods, so each time importing from different files would be confusing, having an index file where all methods were already exported so user can just import the index file.

**Comment by takanome-dev** [comment]
So that mean this is kinda like a package where all those classes can be import by a user?
I thought that this is an api like others (because of the scraping thing)  where a user can query sounds...
